global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'sonarqube'
    metrics_path: /api/monitoring/metrics
    static_configs:
      - targets: ['host.docker.internal:9000']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['host.docker.internal:5000']
