global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['172.21.105.245:8080']

  - job_name: 'sonarqube'
    metrics_path: /api/monitoring/metrics
    static_configs:
      - targets: ['172.21.105.245:9000']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['172.21.105.245:5000']

  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['172.21.105.245:9323']

